/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: antonmoek (https://sketchfab.com/antonmoek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-plane-f312ec9f87794bdd83630a3bc694d8ea
Title: Cartoon Plane
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const CartoonPlane = forwardRef((props, ref) => {
  
  const { nodes, materials, animations } = useGLTF('/models/cartoon_plane-transformed.glb')
  const { actions } = useAnimations(animations, ref)

  useFrame((state, delta) => {
    actions.Main.play()
  })

  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Sketchfab_Scene" rotation={[-Math.PI / 2, Math.PI / 2, Math.PI / 2]} scale={0.8}>
        <group name="RootNode" scale={0.002}>
          <group name="Propeller_1" position={[0.873, -46.025, 401.434]}>
            <mesh name="Propeller_1_Red_0" geometry={nodes.Propeller_1_Red_0.geometry} material={materials.PaletteMaterial001} />
          </group>
        </group>
        <mesh name="Cylinder_1_Body_0" geometry={nodes.Cylinder_1_Body_0.geometry} material={materials.PaletteMaterial001} position={[0.016, -0.264, -0.629]} rotation={[-1.401, 0.021, -1.574]} scale={0.002} />
      </group>
    </group>
  )
})

export default CartoonPlane
useGLTF.preload('/models/cartoon_plane-transformed.glb')
