/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MdTazbi (https://sketchfab.com/Md..Tazbi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/floating-island-44e57137c8344f24a8998d2474403e43
Title: Floating Island
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FloatingSteps(props) {
  const { nodes, materials } = useGLTF('/models/floating_island_steps-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Island_1_Material_0.geometry} material={materials.Material} position={[-1.512, 3.015, -0.193]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/floating_island_steps-transformed.glb')
