/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: CatgirlNotLive (https://sketchfab.com/CatgirlNotLive)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-floating-island-7a35716ec71b4bf8aadf40cd139e1902
Title: Low-Poly Floating Island
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function FloatingIslandWater(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/low-poly_floating_island-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="Island" position={[0, 40.19, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="Island_Grass_0" geometry={nodes.Island_Grass_0.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Island_Water_0" geometry={nodes.Island_Water_0.geometry} material={materials.PaletteMaterial002} />
          </group>
        </group>
        <mesh name="Clouds__0" geometry={nodes.Clouds__0.geometry} material={materials.PaletteMaterial001} position={[-16.453, -3.153, 10.692]} rotation={[-0.913, -0.689, 0.278]} scale={2.747} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/low-poly_floating_island-transformed.glb')
