/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: zhixson (https://sketchfab.com/zhixson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/obligatory-chest-b2318792204f403aa80c92bee68f9c29
Title: Obligatory Chest
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FloatingChest(props) {
  const { nodes, materials } = useGLTF('/models/obligatory_chest-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/obligatory_chest-transformed.glb')
