/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 flying_carpet.glb --transform
Author: Elin (https://sketchfab.com/ElinHohler)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/flying-carpet-2be3311db3724f268179e9cf696df743
Title: Flying Carpet
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export const FlyingCarpet = forwardRef((props, ref) => {
    const { nodes, materials, animations } = useGLTF('/models/player-transformed.glb')
    const { actions } = useAnimations(animations, ref)

    useFrame((state, delta) => {
        actions.Action.play()
    })

    return <group ref={ref} {...props} dispose={null}>
        <group name="Scene" rotation={[-Math.PI / 2, -Math.PI / 2, -Math.PI / 2]} scale={0.35}>
        <group name="GLTF_created_0" position={[0, 0.315, 0]}>
            <primitive object={nodes.GLTF_created_0_rootJoint} />
        </group>
        <mesh name="polySurface11_Ears_0" geometry={nodes.polySurface11_Ears_0.geometry} material={materials.Ears} position={[-0.222, 1.139, -1.001]} rotation={[-1.75, 0.192, -0.813]} scale={0.092} />
        <mesh name="polySurface13_InnerEar_0" geometry={nodes.polySurface13_InnerEar_0.geometry} material={materials.InnerEar} position={[-0.207, 1.128, -1.022]} rotation={[-1.75, 0.192, -0.813]} scale={[0.062, 0.025, 0.062]} />
        <mesh name="pSphere5_Snout_0" geometry={nodes.pSphere5_Snout_0.geometry} material={materials.Snout} position={[0.024, 0.987, -0.955]} rotation={[-0.708, -0.694, -0.501]} scale={[0.128, 0.102, 0.102]} />
        <mesh name="pSphere6_Body_0" geometry={nodes.pSphere6_Body_0.geometry} material={materials.Body} position={[-0.087, 1.103, -0.854]} rotation={[0, -0.831, 0]} scale={0.212} />
        <mesh name="pSphere8_Eyes_0" geometry={nodes.pSphere8_Eyes_0.geometry} material={materials.Eyes} position={[0.092, 1.099, -0.946]} rotation={[0, -0.831, 0]} scale={0.023} />
        <mesh name="pSphere9_Nose_0" geometry={nodes.pSphere9_Nose_0.geometry} material={materials.Nose} position={[0.077, 1.049, -1.001]} rotation={[0.977, -0.549, 0.659]} scale={[0.031, 0.024, 0.024]} />
        <mesh name="polySurface5_Hands_0" geometry={nodes.polySurface5_Hands_0.geometry} material={materials.Hands} position={[-0.345, 1.021, -0.955]} rotation={[1.06, -1.341, 0.552]} scale={0.058} />
        <mesh name="polySurface9_lambert1_0" geometry={nodes.polySurface9_lambert1_0.geometry} material={materials.lambert1} position={[-0.262, 0.807, -0.965]} rotation={[1.602, 0.006, 0.168]} scale={0.091} />
        <mesh name="polySurface19_Leg_0" geometry={nodes.polySurface19_Leg_0.geometry} material={materials.material} position={[-0.272, 0.486, -0.864]} rotation={[Math.PI / 2, 0, -0.648]} scale={0.11} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Carpet} skeleton={nodes.Object_7.skeleton} position={[0, 0.315, 0]} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Tassels} skeleton={nodes.Object_9.skeleton} position={[0, 0.315, 0]} />
        </group>
    </group>
})

useGLTF.preload('/models/player-transformed.glb')
