/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Theristis (https://sketchfab.com/theristis)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/sky-island-lowpoly-d41d523c80624a0aa85df706ebdc6a8f
Title: Sky Island LowPoly
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function SkyIsland(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/sky_island_lowpoly-transformed.glb')
  const { actions } = useAnimations(animations, group)

  useFrame((state, delta) => {
    actions["Propeller|PropellerAction"].play()
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="Camera" position={[14.268, 3000, 10999.039]} rotation={[-3.142, 1.57, 2.862]} scale={100} />
        </group>
        <group name="Wind_turbine" position={[-12.789, 13.503, -3.094]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Propeller" position={[1.014, 0, 3.186]} rotation={[-0.019, 0, 0]}>
            <mesh name="Propeller_White_0" geometry={nodes.Propeller_White_0.geometry} material={materials.PaletteMaterial001} />
          </group>
        </group>
        <group name="Light_House" position={[3.367, 6.303, 13.156]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
          <group name="Spot" position={[0, 0, 3.8]} rotation={[-Math.PI, 0, 0.001]} />
        </group>
        <mesh name="Big_tree_Wood_0" geometry={nodes.Big_tree_Wood_0.geometry} material={materials.PaletteMaterial001} position={[6.846, 6.353, 3.301]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/sky_island_lowpoly-transformed.glb')
